-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 21:33:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema monitoramentoconsumodeagua
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monitoramentoconsumodeagua
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitoramentoconsumodeagua` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `monitoramentoconsumodeagua` ;

-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`hidrometro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`hidrometro` (
  `num_serie_hidrometro` VARCHAR(50) NOT NULL,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`num_serie_hidrometro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`leitura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`leitura` (
  `cod_leitura` INT NOT NULL,
  `valor_medido` DECIMAL(10,3) NOT NULL,
  `data_hora_leitura` DATETIME NOT NULL,
  `num_serie_hidrometro` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_leitura`),
  INDEX `idx_leitura_hidrometro` (`num_serie_hidrometro` ASC) VISIBLE,
  INDEX `idx_leitura_data` (`data_hora_leitura` ASC) VISIBLE,
  CONSTRAINT `fk_leitura_hidrometro`
    FOREIGN KEY (`num_serie_hidrometro`)
    REFERENCES `monitoramentoconsumodeagua`.`hidrometro` (`num_serie_hidrometro`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`alerta` (
  `cod_alerta` INT NOT NULL,
  `data_hora_alerta` DATETIME NOT NULL,
  `tipo_alerta` VARCHAR(100) NOT NULL,
  `cod_leitura` INT NOT NULL,
  PRIMARY KEY (`cod_alerta`),
  INDEX `idx_alerta_leitura` (`cod_leitura` ASC) VISIBLE,
  INDEX `idx_alerta_data` (`data_hora_alerta` ASC) VISIBLE,
  CONSTRAINT `fk_alerta_leitura`
    FOREIGN KEY (`cod_leitura`)
    REFERENCES `monitoramentoconsumodeagua`.`leitura` (`cod_leitura`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`endereco` (
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(255) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`imovel` (
  `cod_imovel` VARCHAR(20) NOT NULL,
  `tipo_imovel` VARCHAR(100) NULL DEFAULT NULL,
  `cep_endereco` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_imovel`),
  INDEX `idx_imovel_cep` (`cep_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_imovel_endereco`
    FOREIGN KEY (`cep_endereco`)
    REFERENCES `monitoramentoconsumodeagua`.`endereco` (`cep`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`usuario` (
  `cod_usuario` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `data_cadastro` DATETIME NULL DEFAULT NULL,
  `tipo_p` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_usuario`),
  UNIQUE INDEX `senha` (`senha` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`contrato` (
  `cod_contrato` INT NOT NULL,
  `cod_usuario` VARCHAR(20) NOT NULL,
  `cod_imovel` VARCHAR(20) NOT NULL,
  `num_serie_hidrometro` VARCHAR(50) NOT NULL,
  `data_inicio` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_contrato`),
  INDEX `idx_contrato_usuario` (`cod_usuario` ASC) VISIBLE,
  INDEX `idx_contrato_imovel` (`cod_imovel` ASC) VISIBLE,
  INDEX `idx_contrato_hidrometro` (`num_serie_hidrometro` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_hidrometro`
    FOREIGN KEY (`num_serie_hidrometro`)
    REFERENCES `monitoramentoconsumodeagua`.`hidrometro` (`num_serie_hidrometro`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contrato_imovel`
    FOREIGN KEY (`cod_imovel`)
    REFERENCES `monitoramentoconsumodeagua`.`imovel` (`cod_imovel`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contrato_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `monitoramentoconsumodeagua`.`usuario` (`cod_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`grupo` (
  `cod_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cod_grupo`),
  UNIQUE INDEX `nome_grupo` (`nome_grupo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`grupos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`grupos_usuarios` (
  `cod_usuario` VARCHAR(20) NOT NULL,
  `cod_grupo` INT NOT NULL,
  `data_entrada` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cod_usuario`, `cod_grupo`),
  INDEX `fk_grupousu_grupo` (`cod_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupousu_grupo`
    FOREIGN KEY (`cod_grupo`)
    REFERENCES `monitoramentoconsumodeagua`.`grupo` (`cod_grupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_grupousu_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `monitoramentoconsumodeagua`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`pessoa_fisica` (
  `cod_usuario` VARCHAR(20) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `data_nasc` DATE NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_pf_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `monitoramentoconsumodeagua`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `monitoramentoconsumodeagua`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`pessoa_juridica` (
  `cod_usuario` VARCHAR(20) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  UNIQUE INDEX `cnpj` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_pj_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `monitoramentoconsumodeagua`.`usuario` (`cod_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `monitoramentoconsumodeagua` ;

-- -----------------------------------------------------
-- Placeholder table for view `monitoramentoconsumodeagua`.`vw_alertas_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`vw_alertas_usuario` (`nome` INT, `data_hora_alerta` INT, `tipo_alerta` INT, `cod_leitura` INT, `valor_medido` INT, `data_hora_leitura` INT, `num_serie_hidrometro` INT);

-- -----------------------------------------------------
-- Placeholder table for view `monitoramentoconsumodeagua`.`vw_dados_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`vw_dados_usuario` (`cod_usuario` INT, `nome` INT, `email` INT, `data_cadastro` INT, `tipo_p` INT, `cpf` INT, `cnpj` INT);

-- -----------------------------------------------------
-- Placeholder table for view `monitoramentoconsumodeagua`.`vw_leituras_por_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitoramentoconsumodeagua`.`vw_leituras_por_usuario` (`nome` INT, `valor_medido` INT, `data_hora_leitura` INT, `num_serie_hidrometro` INT);

-- -----------------------------------------------------
-- function consumo_medio_usuario
-- -----------------------------------------------------

DELIMITER $$
USE `monitoramentoconsumodeagua`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `consumo_medio_usuario`(p_cod_usuario VARCHAR(20)) RETURNS decimal(10,3)
    DETERMINISTIC
BEGIN
    DECLARE hidrometro_usuario VARCHAR(50);
    DECLARE media_consumo DECIMAL(10,3);

    SELECT num_serie_hidrometro INTO hidrometro_usuario
    FROM Contrato
    WHERE cod_usuario = p_cod_usuario
    LIMIT 1;

    SELECT AVG(valor_medido) INTO media_consumo
    FROM Leitura
    WHERE num_serie_hidrometro = hidrometro_usuario;

    RETURN media_consumo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure criar_contrato
-- -----------------------------------------------------

DELIMITER $$
USE `monitoramentoconsumodeagua`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `criar_contrato`(
    IN p_cod_usuario VARCHAR(20),
    IN p_cod_imovel VARCHAR(20),
    IN p_num_serie_hidrometro VARCHAR(50),
    IN p_data_inicio DATETIME,
    IN p_status VARCHAR(50)
)
BEGIN
    DECLARE usuario_existente INT;
    DECLARE hidrometro_existente INT;

    SELECT COUNT(*) INTO usuario_existente
    FROM Usuario
    WHERE cod_usuario = p_cod_usuario;

    SELECT COUNT(*) INTO hidrometro_existente
    FROM Hidrometro
    WHERE num_serie_hidrometro = p_num_serie_hidrometro;

    IF usuario_existente = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Usuário não existe';
    ELSEIF hidrometro_existente = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Hidrometro não existe';
    ELSE
    
        INSERT INTO Contrato (cod_usuario, cod_imovel, num_serie_hidrometro, data_inicio, status)
        VALUES (p_cod_usuario, p_cod_imovel, p_num_serie_hidrometro, p_data_inicio, p_status);
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function gerar_id
-- -----------------------------------------------------

DELIMITER $$
USE `monitoramentoconsumodeagua`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `gerar_id`(tipo_prefixo VARCHAR(5), tamanho INT) RETURNS varchar(255) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
    DECLARE chars_str VARCHAR(62) DEFAULT 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    DECLARE result_str VARCHAR(255) DEFAULT '';
    DECLARE i INT DEFAULT 0;
    DECLARE rand_index INT;
    DECLARE prefixo VARCHAR(255) DEFAULT CONCAT(tipo_prefixo, '_');

    WHILE i < tamanho DO
        SET rand_index = FLOOR(1 + (RAND() * 62));
        SET result_str = CONCAT(result_str, SUBSTRING(chars_str, rand_index, 1));
        SET i = i + 1;
    END WHILE;

    RETURN CONCAT(prefixo, result_str);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `monitoramentoconsumodeagua`.`vw_alertas_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoramentoconsumodeagua`.`vw_alertas_usuario`;
USE `monitoramentoconsumodeagua`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `monitoramentoconsumodeagua`.`vw_alertas_usuario` AS select `u`.`nome` AS `nome`,`a`.`data_hora_alerta` AS `data_hora_alerta`,`a`.`tipo_alerta` AS `tipo_alerta`,`l`.`cod_leitura` AS `cod_leitura`,`l`.`valor_medido` AS `valor_medido`,`l`.`data_hora_leitura` AS `data_hora_leitura`,`l`.`num_serie_hidrometro` AS `num_serie_hidrometro` from (((`monitoramentoconsumodeagua`.`usuario` `u` join `monitoramentoconsumodeagua`.`contrato` `c` on((`c`.`cod_usuario` = `u`.`cod_usuario`))) join `monitoramentoconsumodeagua`.`leitura` `l` on((`l`.`num_serie_hidrometro` = `c`.`num_serie_hidrometro`))) join `monitoramentoconsumodeagua`.`alerta` `a` on((`a`.`cod_leitura` = `l`.`cod_leitura`)));

-- -----------------------------------------------------
-- View `monitoramentoconsumodeagua`.`vw_dados_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoramentoconsumodeagua`.`vw_dados_usuario`;
USE `monitoramentoconsumodeagua`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `monitoramentoconsumodeagua`.`vw_dados_usuario` AS select `u`.`cod_usuario` AS `cod_usuario`,`u`.`nome` AS `nome`,`u`.`email` AS `email`,`u`.`data_cadastro` AS `data_cadastro`,`u`.`tipo_p` AS `tipo_p`,`pf`.`cpf` AS `cpf`,`pj`.`cnpj` AS `cnpj` from ((`monitoramentoconsumodeagua`.`usuario` `u` left join `monitoramentoconsumodeagua`.`pessoa_fisica` `pf` on((`pf`.`cod_usuario` = `u`.`cod_usuario`))) left join `monitoramentoconsumodeagua`.`pessoa_juridica` `pj` on((`pj`.`cod_usuario` = `u`.`cod_usuario`)));

-- -----------------------------------------------------
-- View `monitoramentoconsumodeagua`.`vw_leituras_por_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monitoramentoconsumodeagua`.`vw_leituras_por_usuario`;
USE `monitoramentoconsumodeagua`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `monitoramentoconsumodeagua`.`vw_leituras_por_usuario` AS select `u`.`nome` AS `nome`,`l`.`valor_medido` AS `valor_medido`,`l`.`data_hora_leitura` AS `data_hora_leitura`,`l`.`num_serie_hidrometro` AS `num_serie_hidrometro` from ((`monitoramentoconsumodeagua`.`usuario` `u` join `monitoramentoconsumodeagua`.`contrato` `c` on((`c`.`cod_usuario` = `u`.`cod_usuario`))) join `monitoramentoconsumodeagua`.`leitura` `l` on((`l`.`num_serie_hidrometro` = `c`.`num_serie_hidrometro`)));
USE `monitoramentoconsumodeagua`;

DELIMITER $$
USE `monitoramentoconsumodeagua`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `monitoramentoconsumodeagua`.`trg_alerta_consumo_alto`
AFTER INSERT ON `monitoramentoconsumodeagua`.`leitura`
FOR EACH ROW
BEGIN
    IF NEW.valor_medido > 500 THEN
        INSERT INTO Alerta (tipo_alerta, cod_leitura)
        VALUES ('Consumo alto detectado', NEW.cod_leitura);
    END IF;
END$$

USE `monitoramentoconsumodeagua`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `monitoramentoconsumodeagua`.`trg_alerta_valor_invalido`
AFTER INSERT ON `monitoramentoconsumodeagua`.`leitura`
FOR EACH ROW
BEGIN
    IF NEW.valor_medido < 0 THEN
        INSERT INTO Alerta (tipo_alerta, cod_leitura)
        VALUES ('Leitura inválida', NEW.cod_leitura);
    END IF;
END$$

USE `monitoramentoconsumodeagua`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `monitoramentoconsumodeagua`.`trg_update_leitura`
BEFORE UPDATE ON `monitoramentoconsumodeagua`.`leitura`
FOR EACH ROW
BEGIN  SET NEW.data_hora_leitura = NOW();
END$$

USE `monitoramentoconsumodeagua`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `monitoramentoconsumodeagua`.`trg_alerta_hora_alerta`
BEFORE INSERT ON `monitoramentoconsumodeagua`.`alerta`
FOR EACH ROW
BEGIN SET NEW.data_hora_alerta = NOW();
END$$

USE `monitoramentoconsumodeagua`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `monitoramentoconsumodeagua`.`trg_usuario_data_cadastro`
BEFORE INSERT ON `monitoramentoconsumodeagua`.`usuario`
FOR EACH ROW
BEGIN SET NEW.data_cadastro = NOW();
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
